[package]
name = "client"
version = "0.1.0"
authors = ["Peter Doherty <pdoherty@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = { version = "0.3", default-features = false }
